# Generated by Django 5.0.1 on 2025-09-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0002_document"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="document",
            constraint=models.UniqueConstraint(fields=("user", "url", "content_hash"), name="unique_doc_per_hash"),
        ),
    ]
